### ISSUE TITLE
登录注册页面样式不统一

### ISSUE THREAD

**Issue by qiuwanwani** [Daymychen/art-design-pro#22]
## login\index.scss 的 .right-wrap 替换如下：

```scss
  .right-wrap {
    position: relative;
    flex: 1;
    height: 100%;
  
    .top-right-wrap {
      position: fixed;
      top: 30px;
      right: 30px;
      z-index: 100;
      display: flex;
      align-items: center;
      justify-content: flex-end;

      .btn {
        display: inline-block;
        padding: 5px;
        margin-left: 15px;
        cursor: pointer;
        user-select: none;
        transition: all 0.3s;
  
        i {
          font-size: 18px;
        }
  
        &:hover {
          color: var(--main-color) !important;
        }
      }
    }
  
    .header {
      display: none;
    }
  
    .login-wrap {
      position: absolute;
      inset: 0;
      width: 440px;
      height: 610px;
      padding: 0 5px;
      margin: auto;
      overflow: hidden;
      background-size: cover;
      border-radius: 5px;
  
      .form {
        box-sizing: border-box;
        height: 100%;
        padding: 40px 0;
  
        .title {
          margin-left: -2px;
          font-size: 34px;
          font-weight: 600;
          color: var(--art-text-gray-900) !important;
        }
  
        .sub-title {
          margin-top: 10px;
          font-size: 14px;
          color: var(--art-text-gray-500) !important;
        }
  
        .input-wrap {
          margin-top: 25px;
  
          .input-label {
            display: block;
            padding-bottom: 8px;
            font-size: 15px;
            font-weight: 500;
            color: var(--art-text-gray-800);
          }
        }
  
        .el-input,
        .login-btn {
          height: 46px;
        }
  
        .drag-verify {
          position: relative;
          padding-bottom: 25px;
          margin-top: 25px;
  
          .drag-verify-content {
            position: relative;
            z-index: 2;
            box-sizing: border-box;
            user-select: none;
            border-radius: 8px;
            transition: all 0.3s;
  
            &.error {
              border-color: #f56c6c;
            }
          }
  
          .error-text {
            position: absolute;
            top: 0;
            z-index: 1;
            margin-top: 10px;
            font-size: 13px;
            color: #f56c6c;
            transition: all 0.3s;
  
            &.show-error-text {
              transform: translateY(40px);
            }
          }
        }
  
        .forget-password {
          display: flex;
          align-items: center;
          justify-content: space-between;
          font-size: 14px;
          color: var(--art-text-gray-500);
  
          a {
            color: var(--main-color);
            text-decoration: none;
          }
        }
  
        .login-btn {
          width: 100%;
          color: #fff;
          border: 0;
        }
  
        .footer {
          margin-top: 20px;
          font-size: 14px;
          color: var(--art-text-gray-500);
  
          a {
            color: var(--main-color);
            text-decoration: none;
          }
        }
      }
    }
  }
```

---

## register\index.scss 的 .form 替换如下：

```scss
      .form {
        .el-form {
          margin-top: 25px;
          .el-form-item {
            margin-bottom: 25px;
          }
        }

        .privacy-policy {
          margin-top: 15px;

          :deep(.el-checkbox__label) {
            color: #333 !important;
          }

          a {
            color: var(--main-color);
            text-decoration: none;
          }
        }

        .register-btn {
          width: 100%;
          height: 46px;
          margin-top: 5px;
        }
      }
```
